### ISSUE TITLE
Proper contract support for 0.20

### ISSUE THREAD

**Issue by ethanfrey** [confio/tgrade#156]
There are a number of things left as TODO from #155 

1. [x] We will need some more fields in the genesis file. These are all marked with TODO in bootstrap.go #167 
2. There is another contract auto-created from the valset contract to handle distributions of the validators (they must get their stake and withdraw there). 
    - [x] This address should be registered during bootstrap process, #165 
    - [X] and we should direct withdrawal/distribution queries there (they don't send every block)  #166 
3. [x] Re-enable commented out system tests to properly handle new reward distribution
4. [ ] Update distribution queries/msgs to use those values #170 

Ethan: Add distribution query/msg bindings for the contract (TG4Engagement) so Alex can build on this
